name: 'Check Branch'

on:
  pull_request:
    branches:
      - main

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: startsWith(github.ref, 'refs/heads/release/*') == false
        run: |
          echo "ERROR: You can only merge to main from release branches."
          exit 1
