name: Deploy to Staging

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          if [[ "${{ github.event.inputs.branch }}" != "release/"* ]]; then
            echo "ERROR: You can only deploy from release branches."
            exit 1
          fi
