name: Deploy to Staging

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [[ $BRANCH_NAME != "release/"* ]]; then
            echo "ERROR: You can only deploy from release branches."
            exit 1
          fi
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your deployment steps here
